camunda.bpm:
  admin-user:
    id: kermit
    password: superSecret
    firstName: Kermit
  filter:
    create: All tasks

camunda:
  bpm:
    license-file: "file:${user.home}/.camunda/license.txt"


#logging:
#  level:
#    org:
#      camunda:
#        bpm: TRACE